version: '3.8'

services:
  app: # Nome do serviço para a aplicação Node.js
    container_name: api-todo
    build: . # Diretório onde o Dockerfile está localizado
    ports:
      - "3333:3333" # Mapeamento de porta (host:container)
    environment:
      - NODE_ENV=production
      - PORT=3333
      - DATABASE_URL=postgres://postgres:docker@postgres:5432/primeiro-desafio-pg-prod?schema=public
  
    depends_on:
      - postgres

  postgres:
    container_name: primeiro-desafio-pg-prod
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: primeiro-desafio-pg-prod
      PGDATA: /data/postgres-prod
    volumes:
      - ./data/pg-prod:/data/postgres-prod
    
